let draftShots=[];
const $=id=>document.getElementById(id),form=$('brief-form');
let catalog=[],selectedCaseId='qing',viewedCaseId='qing',optimizedFor=null;
let current=null,files=[],useExample=false,reuseFrom=null,pollTimer=null,tab='video',sample=null,studioLoaded=null;
let selectionRequest=0,renderSubmitting=false;
const names={awaiting_confirmation:'待确认分镜',queued:'排队中',composing:'正在搭建画面',checking:'检查画面与动画',rendering:'正在渲染视频',complete:'已完成',failed:'生成未完成'};
function readSettings(){return {duration:Number($('setting-duration').value),aspect:$('setting-aspect').value,quality:$('setting-quality').value};}
function revealExtraction(){ $('extracted').hidden=false;$('extracted').open=true; }
async function api(url,options={}){const response=await fetch(url,{signal:AbortSignal.timeout(75000),...options});const data=await response.json();if(!response.ok)throw Error(data.error||'操作未完成，请重试');return data;}
function error(id,message){$(id).textContent=message||'';$(id).hidden=!message;}
function readBrief(){return {theme:$('setting-theme').value,brand:form.elements.brand.value,brandLatin:form.elements.brandLatin.value,product:form.elements.product.value,benefits:[1,2,3].map(n=>form.elements['benefit'+n].value),hook:form.elements.hook.value,cta:form.elements.cta.value};}
function fillBrief(b){for(const key of ['brand','brandLatin','product','hook','cta'])form.elements[key].value=b[key]||'';[1,2,3].forEach(n=>form.elements['benefit'+n].value=b.benefits?.[n-1]||'');}
function switchTab(name){tab=name;document.querySelector('.actions').hidden=name==='studio';$('edit-storyboard').hidden=name==='plan';for(const button of document.querySelectorAll('[data-tab]')){const yes=button.dataset.tab===name;button.classList.toggle('active',yes);button.setAttribute('aria-selected',String(yes));button.tabIndex=yes?0:-1;}for(const panel of ['video','plan','studio'])$('panel-'+panel).hidden=panel!==name;document.querySelector('.workspace').classList.toggle('studio-mode',name==='studio');}
function imagePreviews(urls,note){$('image-preview').replaceChildren(...urls.map(url=>{const img=document.createElement('img');img.src=url;img.alt='已选择的商品图片';return img;}));$('asset-note').textContent=note;$('clear-images').hidden=!urls.length;}
let objectUrls=[];
function releaseUrls(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];}
function chooseFiles(list){const next=Array.from(list);if(next.length>12)return error('form-error','最多选择十二张图片');if(next.some(f=>f.size>8*1024*1024))return error('form-error','每张图片不能超过 8 MB');if(next.some(f=>!['image/png','image/jpeg','image/webp'].includes(f.type)))return error('form-error','请选择 PNG、JPEG 或 WebP 图片');releaseUrls();files=next;useExample=false;reuseFrom=null;objectUrls=files.map(f=>URL.createObjectURL(f));imagePreviews(objectUrls,`${files.length} 张图片 · 在分镜中分配`);error('form-error','');}
$('images').addEventListener('change',e=>chooseFiles(e.target.files));
const drop=$('drop-zone');for(const event of ['dragenter','dragover'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.add('dragging');});for(const event of ['dragleave','drop'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.remove('dragging');});drop.addEventListener('drop',e=>chooseFiles(e.dataTransfer.files));
$('clear-images').onclick=()=>{releaseUrls();files=[];useExample=false;reuseFrom=null;$('images').value='';imagePreviews([],'可在分镜中为每个镜头选择图片');};
function renderLegacyPlan(p){$('add-shot').hidden=true;$('shot-summary').textContent=p?.storyboard?`${p.storyboard.length} 镜头 · ${p.storyboard.at(-1).end} 秒`:'';$('save-plan').textContent='保存修改';const scenes=p?.storyboard||[{start:0,end:5,title:'开场吸引',headline:'给日常，来点清爽。',copy:'青柠气泡水 · 清爽上线',visual:'主图推进与开场标题'},{start:5,end:10,title:'展示卖点',headline:'青柠气泡水',copy:'青柠香气 / 细密气泡 / 冰爽即刻',visual:'三个卖点交错进入'},{start:10,end:15,title:'品牌收尾',headline:'开启你的清爽时刻',copy:'QING',visual:'品牌与商品收尾'}];$('storyboard').replaceChildren(...scenes.map((s,i)=>{const card=document.createElement('article');card.className='scene-card';const img=document.createElement('img');img.src=p?p.imageUrls[i]:'/sample/image';img.alt=s.title+'图片';const box=document.createElement('div');box.className='scene-content';const meta=document.createElement('div');meta.className='scene-meta';const title=document.createElement('span');title.textContent=`0${i+1} / ${s.title}`;const duration=document.createElement('span');duration.textContent=`${s.start}–${s.end} 秒`;meta.append(title,duration);const editable=p?.id&&['awaiting_confirmation','failed','complete'].includes(p.status);const h=document.createElement(editable?'input':'h4'),copy=document.createElement(editable?'input':'p');if(editable){h.value=s.headline;h.maxLength=i===1?12:18;h.dataset.sceneHeadline=String(i);h.setAttribute('aria-label','第'+(i+1)+'幕标题');copy.value=s.copy;copy.maxLength=i===0?24:i===1?36:14;copy.dataset.sceneCopy=String(i);copy.setAttribute('aria-label','第'+(i+1)+'幕补充文案');copy.placeholder=i===1?'可留空；最多三个卖点，用 / 分隔':'补充文案';copy.title=i===1?'最多三个卖点，每项最多 10 字':'补充文案';for(const el of [h,copy])el.addEventListener('input',()=>{$('save-plan').disabled=false;$('confirm').disabled=false;});}else{h.textContent=s.headline;copy.textContent=s.copy;}const visual=document.createElement('p');visual.textContent=s.visual;box.append(meta,h,copy,visual);card.append(img,box);return card;}));}
function display(p){selectionRequest++;current=p;$('edit-storyboard').disabled=!['awaiting_confirmation','failed','complete'].includes(p.status);$('save-plan').disabled=true;$('confirm').disabled=p.status==='complete';$('plan-help').textContent=['awaiting_confirmation','failed','complete'].includes(p.status)?'调整文案、时长、顺序与图片，保存后生成新版。原版本会保留。':'正在生成，完成后可修改文案并生成新版。';$('render-notice').textContent=p.renderNotice||'';$('render-notice').hidden=!p.renderNotice;$('confirm').textContent=p.renderNotice?'按 Demo 规格生成样片':'确认并生成视频';const done=p.status==='complete',waiting=p.status==='awaiting_confirmation',failed=p.status==='failed',running=!done&&!waiting&&!failed;
 $('project-title').textContent=`${p.brief.brand} · ${p.brief.product}`;$('project-badge').textContent=names[p.status];$('status-panel').hidden=!running;$('status-title').textContent=names[p.status];$('status-percent').textContent=p.status==='rendering'?`${p.progress}%`:'';$('progress').value=p.progress;$('status-detail').textContent=p.status==='queued'?'前一个项目完成后，会自动开始。':p.status==='rendering'?'正在把动画和配乐合成为 MP4，完成后可直接播放。':'输入与分镜已保存，可以留在这里等待。';
 $('confirm').hidden=running;$('confirm').textContent=done?'保存并生成新版':'保存并生成视频';$('save-plan').hidden=running;$('retry').hidden=!failed;$('edit').hidden=running;$('open-studio').hidden=!done;$('download').hidden=!done;$('download-plan').hidden=false;$('download-plan').href=p.storyboardUrl;$('download').href=p.videoUrl?p.videoUrl+'?download=1':'';$('tab-studio').disabled=!done;
 error('result-error',failed?p.error:'');renderPlan(p);
 const video=$('video');video.hidden=!done;$('video-empty').hidden=done;if(done){if(video.getAttribute('src')!==p.videoUrl){video.src=p.videoUrl;video.poster=p.imageUrls[0];video.load();}$('video-caption').textContent=`${p.media?.duration||p.actualSettings?.duration||15} 秒 · ${p.storyboard.length} 镜头 · 1280 × 720 · ${p.source==='example'?'示例素材':'商品素材'}`;}else{video.pause();$('video-caption').textContent='你的成片将在这里显示';}
 $('video-empty').querySelector('h3').textContent=failed?'这次生成未完成':running?'正在制作你的短片':'分镜已准备好';$('video-empty').querySelector('p').textContent=failed?'输入和分镜已保留，你可以重试或修改。':running?'可以先查看分镜方案。':'确认分镜后，开始生成你的视频。';
}
async function refreshHistory(){const list=await api('/api/projects');$('history-count').textContent=`${list.length} 个项目 · 本机保存`;$('history').replaceChildren();if(!list.length){const p=document.createElement('p');p.className='muted';p.textContent='创建后，项目和结果会保存在这里。';$('history').append(p);}for(const p of list.slice(0,8)){const b=document.createElement('button');b.type='button';b.className='history-card'+(current?.id===p.id?' selected':'');const img=document.createElement('img');img.src=p.imageUrls[0];img.alt='';const span=document.createElement('span'),title=document.createElement('strong'),small=document.createElement('small');title.textContent=`${p.brief.brand} · ${p.brief.product}`;small.textContent=names[p.status];span.append(title,small);b.append(img,span);b.onclick=()=>selectProject(p.id);$('history').append(b);}return list;}
function stopPoll(){clearTimeout(pollTimer);pollTimer=null;}
function poll(id,failures=0){stopPoll();pollTimer=setTimeout(async()=>{if(current?.id!==id)return;try{const was=current.status;const p=await api(`/api/projects/${id}`,{signal:AbortSignal.timeout(8000)});if(current?.id!==id)return;display(p);$('refresh-status').hidden=true;if(p.status==='complete'&&was!=='complete')switchTab('video');if(!['complete','failed','awaiting_confirmation'].includes(p.status))poll(id);else await refreshHistory();}catch(e){if(current?.id!==id)return;const next=failures+1;error('result-error',next>=3?'连接暂时中断，已暂停自动刷新。输入和已提交项目仍保留；恢复服务后点击「重新连接」。':'状态暂时无法刷新，正在重试（'+next+'/3）。');$('refresh-status').hidden=next<3;if(next<3)poll(id,next);}},1500*2**failures);}
async function selectProject(id){const ticket=++selectionRequest;try{stopPoll();const p=await api(`/api/projects/${id}`,{signal:AbortSignal.timeout(8000)});if(ticket!==selectionRequest)return;display(p);$('refresh-status').hidden=true;switchTab(p.status==='complete'?'video':'plan');await refreshHistory();if(current?.id===id&&!['complete','failed','awaiting_confirmation'].includes(p.status))poll(id);}catch(e){if(ticket===selectionRequest){error('result-error',e.message);$('refresh-status').hidden=!current;}}}
$('refresh-status').onclick=()=>current&&selectProject(current.id);
async function createFromInput(renderImmediately){
 error('form-error','');const button=$('plan-button');button.disabled=true;button.textContent='正在准备…';
 try{
  if(optimizedFor!==$('description').value)await optimizeInput();
  if(!readBrief().product.trim()){$('description').focus();throw Error('请在描述中告诉我们要展示什么商品，例如「商品是保温杯」。');}
  if(!files.length&&!useExample&&!reuseFrom)throw Error('请添加商品图片，或点击「填入示例」使用案例素材。');
  const data=new FormData();data.set('brief',JSON.stringify(readBrief()));data.set('useExample',String(useExample));data.set('caseId',selectedCaseId);data.set('description',$('description').value);data.set('settings',JSON.stringify(readSettings()));if(reuseFrom)data.set('reuseFrom',reuseFrom);for(const f of files)data.append('images',f);
  const p=await api('/api/projects',{method:'POST',body:data});stopPoll();display(p);switchTab('plan');await refreshHistory();if(renderImmediately)await confirm();
 }catch(e){error('form-error',e.message);}finally{button.disabled=false;button.textContent='生成视频 →';}
}
form.addEventListener('submit',e=>{e.preventDefault();void createFromInput(true);});
async function savePlan(){
 if(!current)return null;const p=current;const heads=[...document.querySelectorAll('[data-scene-headline]')],copies=[...document.querySelectorAll('[data-scene-copy]')];
 if(p.engine==='multishot-v1'){const scenes=readShotEdits();const shape=s=>({id:s.id,headline:s.headline,copy:s.copy,duration:Math.round(s.duration*30),layout:s.layout,image:s.image});if(JSON.stringify(scenes.map(shape))===JSON.stringify(p.storyboard.map(shape)))return p;const revision=await api('/api/projects/'+p.id+'/storyboard',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({storyboard:scenes})});if(current?.id===p.id)display(revision);await refreshHistory();return revision;}
 if(heads.length!==3)return p;
 const scenes=p.storyboard.map((s,i)=>({...s,headline:heads[i].value,copy:copies[i].value}));
 if(scenes.every((s,i)=>s.headline===p.storyboard[i].headline&&s.copy===p.storyboard[i].copy))return p;
 const revision=await api('/api/projects/'+p.id+'/storyboard',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({storyboard:scenes})});if(current?.id===p.id)display(revision);await refreshHistory();return revision;
}
$('save-plan').onclick=async()=>{error('result-error','');$('save-plan').disabled=true;try{await savePlan();$('save-plan').textContent='分镜已保存';}catch(e){error('result-error',e.message);}finally{$('save-plan').disabled=false;}};
async function confirm(){
 if(!current||renderSubmitting)return;renderSubmitting=true;$('confirm').disabled=true;$('retry').disabled=true;error('result-error','');
 try{const draft=await savePlan();if(current?.id!==draft.id)return;if(draft.status==='complete'){switchTab('plan');throw Error('请先修改分镜文案，再生成新版。');}const p=await api('/api/projects/'+draft.id+'/render',{method:'POST'});if(current?.id!==draft.id)return;display(p);switchTab('video');poll(p.id);await refreshHistory();}catch(e){error('result-error',e.message);}finally{renderSubmitting=false;$('confirm').disabled=current?.status==='complete';$('retry').disabled=false;}
}
$('confirm').onclick=confirm;$('retry').onclick=confirm;
async function openStudio(useCurrent=false){if(useCurrent!==true){if(!studioLoaded){$('studio').src='/edit?embedded=1';$('studio-external').href='/edit';studioLoaded='workspace';}switchTab('studio');return;}const id=current?.id;const errorTarget='result-error';$('open-studio').disabled=true;$('tab-studio').disabled=true;error(errorTarget,'');try{let data;if(current?.status==='complete')data=await api('/api/projects/'+id+'/edit',{method:'POST'});else{const caseId=viewedCaseId||'qing';const response=await api('/api/cases/'+caseId+'/edit',{method:'POST'});data=response;}if(id&&current?.id!==id)return;$('studio-external').href=data.url;$('studio').src=data.url+'&embedded=1';studioLoaded=data.projectId;switchTab('studio');}catch(e){error(errorTarget,e.message);}finally{$('open-studio').disabled=false;$('tab-studio').disabled=false;}}
$('open-studio').onclick=()=>openStudio(true);$('import-current-video').onclick=()=>openStudio(true);$('view-plan').onclick=beginEdit;$('edit-storyboard').onclick=beginEdit;
for(const b of document.querySelectorAll('[data-tab]')){b.onclick=()=>b.dataset.tab==='studio'?openStudio():b.dataset.tab==='plan'?beginEdit():switchTab(b.dataset.tab);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const enabled=[...document.querySelectorAll('[data-tab]')].filter(x=>!x.disabled),index=enabled.indexOf(b),next=enabled[(index+(e.key==='ArrowRight'?1:-1)+enabled.length)%enabled.length];next.focus();next.click();};}
renderPlan(null);refreshHistory().then(async list=>{const params=new URLSearchParams(location.search),requested=params.get('work');if(requested&&list.some(p=>p.id===requested)){await selectProject(requested);if(params.get('tab')==='edit')await openStudio();return;}const pending=list.find(p=>['queued','composing','checking','rendering'].includes(p.status));if(pending)selectProject(pending.id);}).catch(e=>error('result-error',e.message));
// Optional app integration: stage the same visible inputs without creating or rendering a project.
const modelContext=document.modelContext,lifecycle=new AbortController();
if(modelContext?.registerTool){
 const registry=[{name:'read_video_project',description:'Read the selected video project.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>current?{id:current.id,status:current.status,brief:current.brief,videoUrl:current.videoUrl}:{status:'sample'}},{name:'stage_video_brief',description:'Fill the visible optional text inputs. Does not create a project or render video.',inputSchema:{type:'object',properties:{brand:{type:'string',maxLength:8},product:{type:'string',maxLength:12},brandLatin:{type:'string',maxLength:14},hook:{type:'string',maxLength:18},cta:{type:'string',maxLength:18},benefits:{type:'array',items:{type:'string',maxLength:10},maxItems:3}},required:['product'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input.product!=='string'||!input.product.trim())throw Error('Product is required');for(const [key,max] of [['brand',8],['product',12],['brandLatin',14],['hook',18],['cta',18]])if(input[key]!==undefined&&(typeof input[key]!=='string'||input[key].length>max))throw Error('Invalid '+key);if(input.benefits!==undefined&&(!Array.isArray(input.benefits)||input.benefits.length>3||input.benefits.some(x=>typeof x!=='string'||x.length>10)))throw Error('Invalid benefits');fillBrief(input);revealExtraction();optimizedFor=$('description').value;return {staged:true,requiresImages:!files.length&&!useExample&&!reuseFrom};}}];
 for(const tool of registry){try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

window.addEventListener('message',e=>{const frame=document.getElementById('studio');if(e.origin===location.origin&&e.source===frame.contentWindow&&e.data?.type==='video-editor-size'&&innerWidth<=800&&Number.isFinite(e.data.height))frame.style.height=Math.max(600,Math.min(5000,e.data.height+2))+'px';});window.addEventListener('resize',()=>{if(innerWidth>800)document.getElementById('studio').style.height='';});
