const $=s=>document.querySelector(s),composer=$('#composer'),input=$('#message'),attachments=$('#images');
let files=[],project=null,poll=null,selected=null,posting=false,opening=false,nativeDocument=null,selectedNode=null,documentRevision=null;
const objectUrls=[];
let presetCatalog=[],chosenPreset=null,shownEvidence='',showAllProjects=false,openSequence=0,projectSummaries=[],shownVoices='';
const rememberedProjects=new Set(JSON.parse(localStorage.getItem('commerce-created-projects')||'[]'));
function rememberProject(id){rememberedProjects.add(id);localStorage.setItem('commerce-created-projects',JSON.stringify([...rememberedProjects]));}
const active=j=>['queued','running'].includes(j.status);
const busy=()=>posting||opening||project?.jobs.some(j=>active(j)&&j.kind!=='export');
const roles={hero:'主体画面',detail:'细节画面',title:'标题',feature:'说明',price:'价格',cta:'结尾提示',caption:'字幕',decoration:'图形'};
const shortError=text=>/^HyperFrames/.test(text||'')?'画面检查未通过，上一有效版本已保留。可以重试或调整要求。':String(text||'').split('\n')[0];
function showError(e){$('#error').textContent=shortError(e.message||e);$('#error').hidden=false;}
async function api(url,options={}){const r=await fetch(url,options),data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data;}
const post=data=>api('/api/commerce-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function thumbnails(){objectUrls.splice(0).forEach(URL.revokeObjectURL);$('#thumbs').replaceChildren(...files.map((f,i)=>{const chip=document.createElement('div');chip.className='file-chip';if(f.type.startsWith('image/')){const img=document.createElement('img');img.src=URL.createObjectURL(f);img.alt=f.name;objectUrls.push(img.src);chip.append(img);}const name=document.createElement('span'),remove=document.createElement('button');name.textContent=f.name;remove.textContent='×';remove.type='button';remove.setAttribute('aria-label','移除 '+f.name);remove.onclick=()=>{files.splice(i,1);thumbnails();};chip.append(name,remove);return chip;}));}
attachments.onchange=()=>{files.push(...attachments.files);attachments.value='';thumbnails();};
async function listProjects(){
 const data=await api('/api/commerce-projects');projectSummaries=data.projects;const commerceIds=new Set(presetCatalog.map(p=>p.id)),sourceIds=new Set(presetCatalog.map(p=>p.sourceProjectId||data.projects.find(source=>!source.preset&&source.currentRevisionId&&source.request.message===p.input)?.id)),seenPresets=new Set();
 const visible=data.projects.filter(p=>{if(p.id===project?.id)return true;if(showAllProjects)return true;if(!p.currentRevisionId)return false;if(p.preset){if(!commerceIds.has(p.preset.id)||seenPresets.has(p.preset.id))return false;seenPresets.add(p.preset.id);return !data.projects.some(other=>other.id===project?.id&&other.preset?.id===p.preset.id);}return sourceIds.has(p.id)&&!data.projects.some(other=>other.preset&&other.preset.id===presetCatalog.find(preset=>preset.sourceProjectId===p.id||preset.input===p.request.message)?.id)||rememberedProjects.has(p.id);});
 $('#projects').replaceChildren(new Option(showAllProjects?'全部工程':'我的作品',''),...visible.map(p=>new Option((p.title||'未命名作品')+(!p.currentRevisionId?'（尚无成片）':''),p.id)),new Option(showAllProjects?'只看创作与商品示例':'查看全部工程（含测试）','__toggle_all__'));$('#projects').value=project?.id||'';
}
function clearPreview(){
 selected=null;selectedNode=null;nativeDocument=null;documentRevision=null;const old=$('#player');old.pause?.();if(old.getAttribute('src')){const player=document.createElement('hyperframes-player');player.id='player';player.setAttribute('controls','');player.hidden=true;old.replaceWith(player);}else old.hidden=true;
 $('#empty').hidden=false;for(const id of ['revision-tools','object-tools','download','package'])$('#'+id).hidden=true;for(const id of ['download','package'])$('#'+id).removeAttribute('href');$('#revisions').replaceChildren();$('#objects').replaceChildren(new Option('自动理解修改目标',''));$('#object-info').textContent='';
}
function preserveLastFrame(player){let ended=false;player.addEventListener('ended',()=>queueMicrotask(()=>{if(!player.isConnected||!(player.duration>0))return;ended=true;player.pause?.();player.seek?.(Math.max(0,player.duration-1/30));}));player.addEventListener('play',()=>{if(ended&&player.currentTime>=player.duration-.07)player.seek?.(0);ended=false;});player.addEventListener('timeupdate',()=>{if(player.currentTime<player.duration-.08)ended=false;});return player;}
function chooseObject(id,seek=false){selectedNode=id||null;$('#objects').value=id||'';const node=nativeDocument?.nodes.find(n=>n.id===id),scene=nativeDocument?.scenes.find(s=>s.id===node?.sceneId),locks=scene?{content:scene.locked,timing:scene.locked,...scene.locks}:{};$('#object-info').textContent=scene?`第 ${nativeDocument.scenes.indexOf(scene)+1} 幕 · ${Object.entries(locks).filter(([,on])=>on).map(([k])=>({content:'内容已锁',layout:'布局已锁',timing:'时长已锁',absolute:'绝对位置已锁'}[k])).join('，')||'可修改'}`:'';if(seek&&node){$('#player').pause?.();$('#player').seek?.((node.startFrame+Math.min(18,node.durationFrames-1))/30);}}
async function loadObjects(r){if(documentRevision===r.id)return;documentRevision=r.id;try{const doc=await api(r.documentUrl);if(documentRevision!==r.id)return;nativeDocument=doc;$('#objects').replaceChildren(new Option('自动理解修改目标',''),...doc.nodes.filter(n=>n.kind!=='audio').map(n=>new Option(`第 ${doc.scenes.findIndex(s=>s.id===n.sceneId)+1} 幕 · ${roles[n.semanticRole]||n.kind}${n.params?.text?' · '+n.params.text.slice(0,28):''}`,n.id)),...(doc.captions||[]).map((c,i)=>new Option('字幕 '+(i+1)+' · '+c.text.slice(0,28),c.id)));chooseObject(doc.nodes.some(n=>n.id===selectedNode)?selectedNode:null);$('#object-tools').hidden=false;}catch(e){documentRevision=null;showError(e);}}
function preview(r){if(!r)return;selected=r.id;const old=$('#player');if(old.getAttribute('src')!==r.previewUrl){old.pause?.();const player=preserveLastFrame(document.createElement('hyperframes-player'));player.id='player';player.setAttribute('controls','');player.setAttribute('src',r.previewUrl);player.style.aspectRatio=r.output.width+'/'+r.output.height;player.addEventListener('ready',()=>{queueMicrotask(()=>player.seek?.(.6));player.iframe?.contentDocument?.addEventListener('click',e=>{const object=e.target.closest('[data-object-id],[id^="obj-"]');if(object)chooseObject(object.dataset.objectId||object.id.slice(4));});},{once:true});old.replaceWith(player);}void loadObjects(r);$('#player').hidden=false;$('#empty').hidden=true;$('#download').hidden=!r.videoUrl;if(r.videoUrl)$('#download').href=r.videoUrl+'?download=1';$('#package').hidden=!r.packageUrl;if(r.packageUrl)$('#package').href=r.packageUrl+'?download=1';}
function draw(){
 if(!project?.currentRevisionId)clearPreview();
 drawVoices();
 drawExampleEvidence();
 if(project){$('#projects').value=project.id;$('#revision-tools').hidden=!project.currentRevisionId;$('#preset-notice').hidden=!project.preset;$('#revisions').replaceChildren(...project.revisions.map((r,i)=>new Option((i+1)+'. '+r.description.slice(0,40)+(r.branch?'（分支）':''),r.id)));selected=selected&&project.revisions.some(r=>r.id===selected)?selected:project.currentRevisionId;$('#revisions').value=selected;preview(project.revisions.find(r=>r.id===selected));$('#messages').replaceChildren(...project.messages.map(m=>{const d=document.createElement('div');d.className='bubble '+m.role;d.textContent=m.role==='assistant'?shortError(m.text):m.text;return d;}));$('#messages').scrollTop=$('#messages').scrollHeight;
 $('#jobs').replaceChildren(...project.jobs.slice(-3).map(j=>{const d=document.createElement('div');d.textContent=(j.kind==='export'?'导出':j.kind==='create'?'创作':'修改')+' · '+(j.status==='complete'?'已完成':j.status==='failed'?shortError(j.error):j.status==='cancelled'?'已取消':j.stage||'排队中');if(active(j)){const c=document.createElement('button');c.textContent='取消';c.onclick=()=>action({action:'cancel',jobId:j.id});d.append(c);}if(j.status==='failed'){const retry=document.createElement('button');retry.textContent='重试';retry.onclick=()=>action({action:'retry',jobId:j.id});d.append(retry);const detail=document.createElement('details'),summary=document.createElement('summary'),log=document.createElement('pre');summary.textContent='失败详情';log.textContent=j.error;detail.append(summary,log);d.append(detail);}return d;}));$('#details').hidden=false;$('#status').textContent=JSON.stringify({projectId:project.id,currentRevisionId:project.currentRevisionId,previewRevisionId:selected,assets:project.assets.length,preset:project.preset?.id||null},null,2);}
 else{$('#messages').replaceChildren();$('#jobs').replaceChildren();$('#status').textContent='';$('#details').hidden=true;$('#preset-notice').hidden=true;}
 const historyView=project?.currentRevisionId&&selected!==project.currentRevisionId;$('#projects').disabled=posting;$('#send').disabled=Boolean(busy()||historyView);$('#send').textContent=posting?'正在提交…':project?.currentRevisionId?'发送修改':'生成视频';$('#composer-hint').textContent=historyView?'恢复此版后可继续修改':project?.currentRevisionId?'继续描述想改的地方':'素材可不填';input.placeholder=project?.currentRevisionId?'想调整什么？':'想做一条怎样的视频？';for(const id of ['restore','undo','redo'])$('#'+id).disabled=Boolean(busy());$('#export').disabled=!selected||project?.jobs.some(j=>j.kind==='export'&&active(j)&&j.baseRevisionId===selected);
}
async function refresh(){if(!project)return;const id=project.id,prior=project.currentRevisionId,data=await api('/api/commerce/'+id);if(project?.id!==id)return;project=data.project;if(prior!==project.currentRevisionId){selected=project.currentRevisionId;void listProjects().catch(showError);}draw();clearTimeout(poll);if(project.jobs.some(active))poll=setTimeout(()=>refresh().catch(showError),1200);}
async function openProject(id){const sequence=++openSequence;opening=true;clearTimeout(poll);project=null;input.value='';files=[];thumbnails();clearPreview();draw();try{const result=await api('/api/commerce/'+id);if(sequence!==openSequence)return;project=result.project;selected=project.currentRevisionId;history.replaceState(null,'','/?project='+id);draw();await listProjects();await refresh();}finally{if(sequence===openSequence){opening=false;draw();}}}
async function action(data){$('#error').hidden=true;try{const result=await post({...data,projectId:project.id,baseRevisionId:project.currentRevisionId,idempotencyKey:crypto.randomUUID()});if(result.project){if(project.currentRevisionId!==result.project.currentRevisionId)selected=result.project.currentRevisionId;project=result.project;}await refresh();return true;}catch(e){showError(e);return false;}}
async function uploadFiles(){if(files.length+project.assets.length>30)throw Error('每个工程最多30个素材');if(files.some(f=>f.size>1024**3))throw Error('每个素材最多1 GiB');for(const [i,f] of files.entries()){$('#send').textContent=`上传 ${i+1}/${files.length}`;await api('/api/commerce/'+project.id+'/assets',{method:'POST',headers:{'x-file-name':encodeURIComponent(f.name)},body:f});}}
composer.onsubmit=async e=>{e.preventDefault();if(busy())return;const message=input.value.trim();if(!message&&!files.length)return;$('#error').hidden=true;posting=true;draw();try{if(project?.currentRevisionId){await uploadFiles();if(await action({action:'patch',message,selectedNodeId:selectedNode})){input.value='';files=[];thumbnails();}}else{if(!project?.auditions?.length)project=(await post({action:'draft',request:{message,inferRequest:true}})).project;selected=null;rememberProject(project.id);history.replaceState(null,'','/?project='+project.id);draw();await uploadFiles();await post({action:'generate',projectId:project.id,message,idempotencyKey:crypto.randomUUID()});input.value='';files=[];thumbnails();await refresh();await listProjects();}}catch(err){showError(err);}finally{posting=false;draw();}};
async function loadPreset(preset){if(busy())return;++openSequence;posting=true;draw();try{project=(await post({action:'preset',presetId:preset.id})).project;selected=project.currentRevisionId;history.replaceState(null,'','/?project='+project.id);input.value=preset.input;files=[];thumbnails();draw();await listProjects();}catch(e){showError(e);}finally{posting=false;draw();}}
$('#regenerate').onclick=async()=>{if(busy()||!project?.preset)return;posting=true;draw();try{const source=project;files=await Promise.all(source.assets.map(async a=>{const r=await fetch('/api/commerce/'+source.id+'/input-assets/'+a.id);if(!r.ok)throw Error('预设输入素材读取失败');return new File([await r.blob()],a.name,{type:r.headers.get('content-type')||'application/octet-stream'});}));input.value=source.request.message;clearTimeout(poll);project=null;selected=null;nativeDocument=null;documentRevision=null;$('#messages').replaceChildren();$('#preset-notice').hidden=true;$('#revision-tools').hidden=true;$('#object-tools').hidden=true;$('#details').hidden=true;$('#jobs').replaceChildren();$('#download').hidden=true;$('#package').hidden=true;$('#player').pause?.();$('#player').hidden=true;$('#empty').hidden=false;history.replaceState(null,'','/');thumbnails();input.focus();}catch(e){showError(e);}finally{posting=false;draw();}};
$('#new-project').onclick=()=>{location.href='/';};$('#projects').onchange=e=>{if(e.target.value==='__toggle_all__'){showAllProjects=!showAllProjects;void listProjects();}else if(e.target.value)openProject(e.target.value).catch(showError);};$('#objects').onchange=e=>chooseObject(e.target.value,true);$('#revisions').onchange=e=>{selected=e.target.value;draw();};$('#restore').onclick=()=>action({action:'restore',revisionId:selected});$('#undo').onclick=()=>action({action:'undo'});$('#redo').onclick=()=>action({action:'redo'});$('#export').onclick=()=>action({action:'export',revisionId:selected});
$('#open-package').onclick=()=>$('#package-file').click();
$('#package-file').onchange=async()=>{const file=$('#package-file').files[0];if(!file)return;$('#package-file').value='';$('#error').hidden=true;$('#open-package').disabled=true;try{const result=await api('/api/commerce-import',{method:'POST',headers:{'Content-Type':'application/zip'},body:file});await openProject(result.project.id);}catch(error){showError(error);}finally{$('#open-package').disabled=false;}};
function chooseExample(id){
 chosenPreset=presetCatalog.find(p=>p.id===id)||null;$('#example-card').hidden=!chosenPreset;if(!chosenPreset)return;
 const p=chosenPreset;$('#example-select').value=p.id;$('#example-category').textContent=p.category+' · '+p.durationSeconds+' 秒 · '+(p.reviewStatus==='draft'?'预览草稿':'预设样片');$('#example-title').textContent=p.title;$('#example-description').textContent=p.description;
 $('#example-tags').replaceChildren(...p.capabilities.map(text=>{const tag=document.createElement('span');tag.textContent=text;return tag;}));$('#example-poster').hidden=!p.poster;if(p.poster)$('#example-poster').src=p.poster;$('#example-load').dataset.presetId=p.id;$('#example-load').disabled=Boolean(busy());
 if(!project)void showLandingExample(p);
}
async function showLandingExample(p){
 if(!projectSummaries.length)await listProjects();if(project||posting||opening||chosenPreset?.id!==p.id)return;
 const source=projectSummaries.find(item=>item.preset?.id===p.id)||projectSummaries.find(item=>item.currentRevisionId&&item.request.message===p.input),revision=source?.revisions.find(r=>r.id===source.currentRevisionId),url=p.previewUrl||revision?.previewUrl;if(!url)return;
 const old=$('#player');old.pause?.();const player=preserveLastFrame(document.createElement('hyperframes-player'));player.id='player';player.setAttribute('controls','');player.setAttribute('src',url);player.style.aspectRatio=p.output.width+'/'+p.output.height;player.addEventListener('ready',()=>{queueMicrotask(()=>player.seek?.(Math.min(2,p.durationSeconds*.15)));},{once:true});old.replaceWith(player);$('#empty').hidden=true;
}
function drawExampleEvidence(){
 $('#example-load').disabled=Boolean(busy());const p=presetCatalog.find(p=>p.id===project?.preset?.id||(p.sourceProjectId===project?.id&&project?.revisions.some(r=>r.id===selected&&r.previewUrl===p.previewUrl)));$('#example-evidence').hidden=!p;if(!p){shownEvidence='';return;}
 const key=project.id+':'+p.id;if(key===shownEvidence)return;shownEvidence=key;
 $('.example-fixed-note').textContent='这是已经生成的固定样片。重新生成会再次理解输入、选材和制作。'+(p.evidenceNote?' '+p.evidenceNote:'');
 $('#example-assets').replaceChildren(...project.assets.map((a,i)=>{const link=document.createElement('a');link.href='/api/commerce/'+project.id+'/input-assets/'+a.id;link.target='_blank';link.rel='noopener';link.title='查看输入素材：'+a.name;const media=document.createElement(a.kind==='image'?'img':'div');if(a.kind==='image'){media.src=link.href;media.alt='输入图片 '+(i+1);}else{media.className='source-video';media.textContent=a.kind==='video'?'▷':'♫';}const name=document.createElement('span');name.textContent=a.name||((a.kind==='image'?'图片 ':a.kind==='video'?'输入视频 ':'音频 ')+(i+1));link.append(media,name);return link;}));
 $('#example-process').replaceChildren(...p.process.map(item=>{const row=document.createElement('li'),title=document.createElement('strong'),detail=document.createElement('p');title.textContent=item.title;detail.textContent=item.detail;row.append(title,detail);return row;}));
 $('#example-beats').replaceChildren(...(p.beats||[]).map(beat=>{const button=document.createElement('button');button.type='button';button.className='quiet';button.textContent=beat.startSeconds.toFixed(1)+'–'+beat.endSeconds.toFixed(1)+' 秒 · '+beat.title;button.onclick=()=>{selected=(project.revisions.find(r=>r.previewUrl===p.previewUrl)||project.revisions[0]).id;draw();const player=$('#player'),seek=()=>{player.pause?.();player.seek?.(Math.min(beat.endSeconds-.1,beat.startSeconds+.8));};if(player.duration>0)seek();else player.addEventListener('ready',()=>queueMicrotask(seek),{once:true});};return button;}));
 $('#example-result').textContent=`已生成 ${p.durationSeconds} 秒 · ${p.output.width}×${p.output.height} · 可编辑原生工程与 MP4`;
 $('#example-credits').replaceChildren(document.createTextNode('素材来源：'),...p.credits.map(c=>{const link=document.createElement('a');link.textContent=c.label;if(/^https:\/\//.test(c.url)){link.href=c.url;link.target='_blank';link.rel='noopener';}return link;}));
}
$('#example-select').onchange=e=>chooseExample(e.target.value);$('#example-load').onclick=()=>{if(chosenPreset)loadPreset(chosenPreset);};
async function refreshExamples(){
 try{const data=await api('/api/commerce-demos'),next=data.presets.filter(p=>p.category&&p.category!=='基础示例'),signature=JSON.stringify(next);if(signature!==JSON.stringify(presetCatalog)){const previous=chosenPreset?.id;presetCatalog=next;$('#example-select').replaceChildren(new Option('选择一个商品场景',''),...presetCatalog.map(p=>new Option(p.title+' · '+p.category,p.id)));if(presetCatalog.length)chooseExample(presetCatalog.some(p=>p.id===previous)?previous:project?.preset?.id||presetCatalog[0].id);shownEvidence='';drawExampleEvidence();void listProjects();}$('#examples-loading').hidden=Boolean(presetCatalog.length);$('#examples-loading').textContent='商品示例正在制作，完成检查后会出现在这里。';}catch(error){if(!presetCatalog.length)$('#examples-loading').textContent='示例暂时无法读取，你仍可输入需求开始创作。';}
 if(presetCatalog.filter(p=>p.reviewStatus!=='draft').length<3)setTimeout(refreshExamples,10000);
}
void refreshExamples();
const initial=new URLSearchParams(location.search).get('project');if(initial)openProject(initial).catch(showError);else listProjects().catch(showError);

function drawVoices(){const voices=project?.auditions||[],key=voices.map(a=>a.id).join('|');if(key===shownVoices)return;shownVoices=key;$('#voice-results').hidden=!voices.length;$('#voice-results').replaceChildren(...voices.map((a,i)=>{const card=document.createElement('div'),label=document.createElement('p'),audio=document.createElement('audio'),button=document.createElement('button');label.textContent='试听 '+(i+1)+' · '+(a.voice.startsWith('zf_')?'女声':'男声');audio.controls=true;audio.preload='metadata';audio.src=a.url;button.type='button';button.className='quiet';button.textContent='选择这个声音';button.onclick=()=>{input.value='确认使用第'+(i+1)+'个声音。';input.focus();};card.append(label,audio,button);return card;}));}
