const $=s=>document.querySelector(s),create=$('#create'),follow=$('#follow'),images=$('#images'),thumbs=$('#thumbs'),messages=$('#messages'),video=$('#video'),download=$('#download'),statusEl=$('#status'),details=$('#details'),errorEl=$('#error');let files=[],projectId=null;
function say(text,who='assistant'){const d=document.createElement('div');d.className=`bubble ${who}`;d.textContent=text;messages.append(d);messages.scrollTop=messages.scrollHeight;}
function showError(e){errorEl.textContent=e.message||String(e);errorEl.hidden=false;}
function thumbsRender(){thumbs.replaceChildren(...files.map(f=>{const i=document.createElement('img');i.src=URL.createObjectURL(f);i.alt='商品图';return i;}));}
images.onchange=()=>{files=[...images.files].slice(0,12);thumbsRender();};
async function api(url,options={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(180000)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
function showResult(id){projectId=id;const src=`/api/commerce/${encodeURIComponent(id)}/video`;video.src=src;video.hidden=false;$('#empty').hidden=true;download.href=src+'?download=1';download.download=`commerce-${id}.mp4`;download.hidden=false;follow.hidden=false;details.hidden=false;statusEl.textContent=`项目 ${id}\n视频：${src}`;}
create.onsubmit=async e=>{e.preventDefault();errorEl.hidden=true;if(!files.length){showError(new Error('请先上传商品图片'));return;}const btn=$('#send');btn.disabled=true;btn.textContent='正在生成…';say(create.message.value||'生成一条商品宣传视频','user');try{const fd=new FormData(create);const d=await api('/api/commerce-chat',{method:'POST',body:fd});showResult(d.result.projectId);say('视频已生成，可以直接播放或继续告诉我怎么修改。');}catch(err){showError(err);say('生成失败：'+err.message);}finally{btn.disabled=false;btn.textContent='生成宣传视频';}};
follow.onsubmit=async e=>{e.preventDefault();errorEl.hidden=true;const input=follow.message, message=input.value.trim();if(!message||!projectId)return;const btn=follow.querySelector('button');btn.disabled=true;say(message,'user');try{const d=await api('/api/commerce-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'patch',projectId,message,render:true})});showResult(d.result.projectId||projectId);say('已按你的要求生成新版本，原工程版本仍保留。');input.value='';}catch(err){showError(err);say('修改失败：'+err.message);}finally{btn.disabled=false;}};
