import {textStyleSegments} from './rich-text.mjs';
import {parse} from 'acorn';
import {parseFragment,serialize} from 'parse5';
import postcss from 'postcss';
import {brandFontResources} from './brand-fonts.mjs';
import {insist} from './contracts.mjs';

const safeId=s=>typeof s==='string'&&/^[a-zA-Z][a-zA-Z0-9_-]{0,63}$/.test(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stringify=value=>JSON.stringify(value).replaceAll('<','\\u003c');
const tags=new Set(['div','span','p','h1','h2','img','svg','g','path','circle','ellipse','rect','line','polyline','polygon','text','defs','clipPath','linearGradient','radialGradient','stop']);
const attrs=new Set(['id','class','viewBox','width','height','x','y','x1','x2','y1','y2','cx','cy','r','rx','ry','d','points','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','stroke-dasharray','stroke-dashoffset','opacity','transform','preserveAspectRatio','clip-path','clipPathUnits','offset','stop-color','stop-opacity','gradientUnits','gradientTransform']);
const cssProperties=new Set(['position','inset','top','right','bottom','left','width','height','max-width','max-height','min-width','min-height','display','align-items','justify-content','flex-direction','gap','padding','margin','box-sizing','background','background-color','color','border','border-color','border-width','border-style','border-radius','box-shadow','overflow','opacity','font-size','font-weight','line-height','letter-spacing','text-align','white-space','transform','transform-origin','fill','stroke','stroke-width','stroke-dasharray','stroke-dashoffset','clip-path','z-index','object-fit','object-position']);
const animationProperties=new Set(['x','y','xPercent','yPercent','scale','scaleX','scaleY','rotation','rotationX','rotationY','opacity','autoAlpha','transformOrigin','strokeDashoffset','strokeDasharray','clipPath','borderRadius','backgroundColor','color','fill','stroke','duration','ease','delay','stagger','repeat','yoyo','immediateRender']);
for(const property of ['flex-shrink','flex-grow','flex-basis','font-family','font-style','text-shadow','flex-wrap','flex','grid-template-columns','grid-template-rows','align-content','align-self','justify-self','overflow-wrap','word-break','aspect-ratio','border-left','border-right','border-top','border-bottom','padding-left','padding-right','padding-top','padding-bottom','margin-left','margin-right','margin-top','margin-bottom'])cssProperties.add(property);
export const CUSTOM_SOURCE_CONTRACT=`受管原创 contractVersion:2。customSourceJson={contractVersion:2,html,css,timeline,parameters:[{name,value,min,max}],objects:[{elementId,ref}],motionTargets:[elementId],textStyles:[{elementId,match,fontSize,fontWeight,color}],tokens:{}}。所有ID用英文字母开头，只含字母数字短横线下划线。ref使用本场text-1/text-2等（按文字数组顺序）或title/feature/price/cta、media-1到media-4、decoration-1等。局部文字层级用textStyles；没有局部样式时为空数组。match必须是该映射原生文字中唯一出现的原文子串，不得新增、改写或重叠。fontSize为12—240，fontWeight为100—900整数，color为六位十六进制颜色。应用生成安全内联样式，原文和对象ID保留。每个文字和图片视图都须唯一映射；同一图片的media-N可映射多个img，应用为局部视图生成独立稳定原生节点，共享同一源素材，每镜头至多4个媒体窗口；视频多窗口必须在分镜media中分别声明，DOM叶文字留空、img不写src，由原生对象注入。视频映射空div，由编译器对应到场景外的非计时视频容器，可用本地#id CSS定义位置、尺寸、裁切与有限视觉动画；不得调用视频play/pause/seek。视频本体、时钟和原声由框架管理。若不映射视频，保留其全画幅底层行为。允许div/span/p/h1/h2/img/svg/g/path/circle/ellipse/rect/line/polyline/polygon/text/defs/clipPath/linearGradient/radialGradient/stop。SVG只可url(#本场ID)片段引用，禁止外部资源/use/foreignObject/script/style/事件。CSS仅本場#id选择器，不允许伪类/全局/@规则/url/animation/transition。允许flex/grid、font-family（已允许本地字体）、普通排版和裁切。tokens由应用的品牌设计注入；仅能var(--brand-background/foreground/panel/accent/accentContrast)，不得自定义其他变量。原生文字分时出现应使用有限timeline，不把所有字同时挤在一屏。timeline仅连续tl.to/from/fromTo/set("#id",{字面量GSAP属性},绝对秒数)，数值可用params.name和+-*/算式；不写变量、函数、循环、异步、回调或API。可用x/y/scale/opacity/rotation/strokeDashoffset/clipPath等视觉属性；禁止播放控制、left/top动画。所有动画结束不超过params.sceneSeconds，可用比例计算。重复0—20的有限整数。motionTargets必须映射原生对象且有真实可见运动；静态关键画面或不需要包装动画的实拍可使用空timeline与空motionTargets，仍执行相同HTML/CSS/AST和隔离检查。params.sceneSeconds是应用注入的只读内置值，绝对不能把sceneSeconds放进parameters数组或声明/覆盖它；不需要自定义参数时parameters=[]。HTML和timeline中的引号按标准JSON编码，不保留多余反斜线。数值参数最多24项，声明min/max；全文本/媒体/时序权威在原生文档，源码不能新增事实。CSS属性白名单：${[...cssProperties].join(", ")}。`;

export function customParameters(bundle,overrides={}){
  insist(Array.isArray(bundle.parameters)&&bundle.parameters.length<=24,'自定义参数数量无效','CUSTOM_PARAMETERS');
  const values={},names=new Set();
  for(const p of bundle.parameters){insist(safeId(p.name)&&!['constructor','prototype','__proto__','sceneSeconds'].includes(p.name)&&!names.has(p.name),'自定义参数名无效：'+p.name+'；sceneSeconds为只读内置参数，不得声明；其他名称须唯一','CUSTOM_PARAMETERS');names.add(p.name);const value=overrides[p.name]??p.value;insist([p.min,p.max,value].every(Number.isFinite)&&p.min>=-20000&&p.max<=20000&&p.min<=value&&value<=p.max,'自定义参数超出声明范围','CUSTOM_PARAMETERS');values[p.name]=value;}
  insist(Object.keys(overrides).every(k=>names.has(k)),'自定义场景不支持这个参数','CUSTOM_PARAMETERS');return values;
}
function valueOf(node,params){
  if(node.type==='Literal'){insist(typeof node.value!=='object'&&['string','number','boolean'].includes(typeof node.value),'不支持的动画字面量','CUSTOM_SCRIPT');return node.value;}
  if(node.type==='UnaryExpression'&&['+','-'].includes(node.operator)){const n=valueOf(node.argument,params);insist(typeof n==='number','无效数值表达式','CUSTOM_SCRIPT');return node.operator==='-'?-n:n;}
  if(node.type==='MemberExpression'&&!node.computed&&node.object.type==='Identifier'&&node.object.name==='params'&&node.property.type==='Identifier'){insist(Object.hasOwn(params,node.property.name),'动画引用未知参数','CUSTOM_PARAMETERS');return params[node.property.name];}
  if(node.type==='BinaryExpression'&&['+','-','*','/'].includes(node.operator)){const a=valueOf(node.left,params),b=valueOf(node.right,params);insist(typeof a==='number'&&typeof b==='number','动画表达式只能计算数字','CUSTOM_SCRIPT');const n=node.operator==='+'?a+b:node.operator==='-'?a-b:node.operator==='*'?a*b:a/b;insist(Number.isFinite(n)&&Math.abs(n)<=1e12,'动画表达式计算溢出或除以零；最终属性值另按20000边界检查','CUSTOM_SCRIPT');return n;}
  if(node.type==='ObjectExpression'){const result={};insist(node.properties.length<=24,'动画属性过多','CUSTOM_SCRIPT');for(const p of node.properties){insist(p.type==='Property'&&!p.computed&&!p.method&&p.kind==='init'&&['Identifier','Literal'].includes(p.key.type),'动画属性必须为普通字面量','CUSTOM_SCRIPT');const name=p.key.name??p.key.value;insist(animationProperties.has(name)&&!Object.hasOwn(result,name),'不支持的动画属性','CUSTOM_SCRIPT');result[name]=valueOf(p.value,params);}return result;}
  insist(false,'源码只能使用有限的GSAP时间线调用','CUSTOM_SCRIPT');
}

/** Parse untrusted source; return regenerated markup/CSS and canonical finite animation calls. No eval. */
export function compileCustomSource(bundle,{scene,nodes,assets={},params=scene.effectParams||{}}){
  insist(bundle&&['html','css','timeline'].every(k=>typeof bundle[k]==='string'&&bundle[k].length<=32000),'自定义源码缺失或过大','CUSTOM_SOURCE');
  const managedMedia=bundle.contractVersion===2;
  const values={...customParameters(bundle,params),sceneSeconds:scene.durationFrames/30},prefix='custom-'+scene.id+'-',tree=parseFragment(bundle.html),ids=new Map();let count=0;
  const errors=[];parseFragment(bundle.html,{onParseError:e=>errors.push(e.code)});insist(errors.length===0,'自定义HTML语法错误','CUSTOM_HTML');
  function visit(parent){for(const node of parent.childNodes||[]){
    if(node.nodeName==='#text'){insist(!node.value.trim(),'自定义文字必须来自原生文字对象','CUSTOM_TEXT');continue;}
    insist(tags.has(node.tagName)&&++count<=160,'自定义HTML含不支持标签或过多元素','CUSTOM_HTML');
    for(const attr of node.attrs){insist(!attr.namespace&&attrs.has(attr.name)&&!/[<>\\]/.test(attr.value),'自定义HTML属性不支持','CUSTOM_HTML');insist(attr.value.length<=6000&&!/(?:url\s*\(|javascript:|data:|https?:|file:)/i.test(attr.value.replace(/^url\(#[a-zA-Z][a-zA-Z0-9_-]*\)$/,'')),'自定义HTML外部引用被禁止','CUSTOM_RESOURCE');}
    const id=node.attrs.find(a=>a.name==='id');if(id){insist(safeId(id.value)&&!ids.has(id.value),'自定义元素ID无效或重复','CUSTOM_HTML');ids.set(id.value,node);id.value=prefix+id.value;}
    visit(node);
  }}visit(tree);
  function rewriteFragments(parent){for(const element of parent.childNodes||[]){for(const attr of element.attrs||[]){const match=/^url\(#([a-zA-Z][a-zA-Z0-9_-]*)\)$/.exec(attr.value);if(match){insist(ids.has(match[1]),'SVG局部引用不存在','CUSTOM_RESOURCE');attr.value='url(#'+prefix+match[1]+')';}}rewriteFragments(element);}}rewriteFragments(tree);

  insist(Array.isArray(bundle.objects)&&bundle.objects.length>=1&&bundle.objects.length<=100,'自定义对象图无效','CUSTOM_OBJECTS');
  const textStyles=bundle.textStyles??[];insist(Array.isArray(textStyles)&&textStyles.length<=32&&textStyles.every(s=>bundle.objects.some(m=>m.elementId===s.elementId&&nodes.some(n=>n.id===m.nodeId&&n.kind==='text'))),'局部样式必须关联本场原生文字对象','CUSTOM_TEXT_STYLE');
  const mapped=new Set(),nodeIds=new Set(),objects=[],videoBindings=new Set();
  for(const mapping of bundle.objects){const element=ids.get(mapping.elementId),native=nodes.find(n=>n.id===mapping.nodeId);insist(element&&native&&!mapped.has(mapping.elementId)&&!nodeIds.has(native.id),'自定义对象映射无效','CUSTOM_OBJECTS');mapped.add(mapping.elementId);nodeIds.add(native.id);objects.push({elementId:mapping.elementId,domId:native.kind==='video'?(managedMedia?'media-wrap-':'obj-')+native.id:prefix+mapping.elementId,nodeId:native.id});element.attrs.push({name:'data-object-id',value:native.id});
    if(native.kind==='text'){insist(['div','span','p','h1','h2','text'].includes(element.tagName)&&!element.childNodes?.some(n=>n.tagName),'文字对象必须为叶节点','CUSTOM_TEXT');element.childNodes=textStyleSegments(native.params.text,textStyles.filter(s=>s.elementId===mapping.elementId)).map(segment=>{if(!segment.style)return {nodeName:'#text',value:segment.text,parentNode:element};const {fontSize,fontWeight,color}=segment.style,tagName=element.tagName==='text'?'tspan':'span',span={nodeName:tagName,tagName,namespaceURI:element.namespaceURI,attrs:[{name:'style',value:'font-size:'+fontSize+'px;font-weight:'+fontWeight+';color:'+color+(tagName==='tspan'?';fill:'+color:'')},{name:'data-text-range',value:segment.start+':'+segment.end}],childNodes:[],parentNode:element};span.childNodes=[{nodeName:'#text',value:segment.text,parentNode:span}];return span;});}
    else if(native.kind==='image'){insist(element.tagName==='img'&&assets[native.assetId],'自定义图片缺少真实素材','CUSTOM_RESOURCE');const ref=assets[native.assetId].compiledRef||assets[native.assetId].ref;insist(/^assets\/[a-zA-Z0-9_.-]+\.(?:png|jpe?g|webp)$/i.test(ref),'自定义图片路径越界','CUSTOM_RESOURCE');element.attrs.push({name:'src',value:ref},{name:'alt',value:''},{name:'data-start',value:String(scene.startFrame/30)},{name:'data-duration',value:String(scene.durationFrames/30)});}
    else if(native.kind==='video'){insist(element.tagName==='div'&&!element.childNodes?.some(n=>n.tagName),'视频须映射到空div，由引擎独立播放','CUSTOM_RESOURCE');videoBindings.add(mapping.elementId);element.attrs.push({name:'style',value:'display:none!important'});}
    else insist(['shape','component'].includes(native.kind),'自定义源码中不支持该媒体类型','CUSTOM_RESOURCE');
  }
  insist(nodes.filter(n=>!['audio','video'].includes(n.kind)).every(n=>nodeIds.has(n.id)),'自定义场景遗漏原生对象','CUSTOM_OBJECTS');
  for(const [id,element] of ids)if(element.tagName==='img')insist(mapped.has(id),'图片必须声明原生素材','CUSTOM_RESOURCE');
  const resolveId=id=>managedMedia&&videoBindings.has(id)?'media-wrap-'+objects.find(o=>o.elementId===id).nodeId:prefix+id;
  const tokenNames=new Set(['background','foreground','panel','accent','accentContrast']);
  const css=bundle.css.replace(/var\(--brand-([a-zA-Z]+)\)/g,(_,name)=>{insist(tokenNames.has(name)&&/^#[0-9a-f]{6}$/i.test(bundle.tokens?.[name]),'品牌变量缺少已声明颜色','CUSTOM_CSS');return bundle.tokens[name];});
  const sheet=postcss.parse(css);let declarations=0;
  sheet.walkAtRules(()=>insist(false,'自定义CSS禁止导入及全局规则','CUSTOM_CSS'));
  sheet.walkRules(rule=>{insist(rule.parent===sheet,'自定义CSS不允许嵌套规则','CUSTOM_CSS');const selectors=rule.selector.split(',').map(s=>s.trim());insist(selectors.every(s=>/^#[a-zA-Z][a-zA-Z0-9_-]*$/.test(s)&&ids.has(s.slice(1))),'CSS只能选择本场景ID','CUSTOM_CSS');rule.selector=selectors.map(s=>(managedMedia&&videoBindings.has(s.slice(1))?'':'#'+scene.id+' ')+'#'+resolveId(s.slice(1))).join(',');});
  sheet.walkDecls(d=>{insist(++declarations<=500&&cssProperties.has(d.prop)&&!d.important&&d.parent.type==='rule','场景 '+scene.id+' 的 CSS 属性不支持：'+d.prop+':'+d.value+'；禁止 !important、嵌套及未列出的属性','CUSTOM_CSS');insist(!/[\\<>@]/.test(d.value)&&!/(?:url\s*\(|expression\s*\(|var\s*\(|image-set\s*\(|(?:https?|data|file):)/i.test(d.value),'自定义CSS外链/动态引用被禁止','CUSTOM_CSS');insist(d.value.length<=300,'CSS值过长','CUSTOM_CSS');if(d.prop!=='font-family')for(const n of d.value.replace(/#[0-9a-f]{3,8}\b/ig,'').matchAll(/[+-]?(?:\d*\.)?\d+(?:e[+-]?\d+)?/gi))insist(Math.abs(Number(n[0]))<=20000,'CSS尺寸超出资源边界','CUSTOM_RESOURCE');if(d.prop==='position')insist(['absolute','relative','static'].includes(d.value),'不支持的定位方式','CUSTOM_CSS');});
  sheet.walkDecls('font-family',d=>{const allowed=['microsoft yahei','arial','pingfang sc','sans-serif','serif','monospace','inherit',...brandFontResources(assets).map(f=>f.family.toLowerCase())];const families=d.value.split(',').map(s=>s.trim().replace(/^["']|["']$/g,'').toLowerCase());if(families.some(f=>!allowed.includes(f)))throw Object.assign(Error('场景 '+scene.id+' 使用未配置字体 '+d.value+'；只能使用工程字体合同列出的本地字体或 Microsoft YaHei / Arial。'),{code:'CUSTOM_FONT_UNAVAILABLE',sceneId:scene.id});});
  const staticLayout=bundle.contractVersion===2&&nodes.length>0&&bundle.timeline.trim()===''&&Array.isArray(bundle.motionTargets)&&bundle.motionTargets.length===0;
  const ast=parse(bundle.timeline,{ecmaVersion:2022});insist((ast.body.length>0||staticLayout)&&ast.body.length<=160,'自定义时间线数量无效','CUSTOM_SCRIPT');const calls=[];
  for(const stmt of ast.body){const call=stmt.expression;insist(stmt.type==='ExpressionStatement'&&call?.type==='CallExpression'&&call.callee.type==='MemberExpression'&&!call.callee.computed&&call.callee.object.type==='Identifier'&&call.callee.object.name==='tl'&&call.callee.property.type==='Identifier'&&['to','from','fromTo','set'].includes(call.callee.property.name),'源码只能包含有限GSAP调用','CUSTOM_SCRIPT');const method=call.callee.property.name;insist(call.arguments.length===(method==='fromTo'?4:3),'GSAP参数数量无效','CUSTOM_SCRIPT');const args=call.arguments.map(n=>valueOf(n,values)),selector=args[0],at=args.at(-1);insist(typeof selector==='string'&&/^#[a-zA-Z][a-zA-Z0-9_-]*$/.test(selector)&&ids.has(selector.slice(1)),'动画只能选择本场景对象','CUSTOM_SCRIPT');
    insist(managedMedia||!videoBindings.has(selector.slice(1)),'视频占位不做动画；实拍由引擎播放，请对独立文字或图形叠层编排动效','CUSTOM_MOTION');
    const vars=args.slice(1,-1);for(const v of vars){insist(v&&typeof v==='object'&&!Array.isArray(v),'GSAP属性对象无效','CUSTOM_SCRIPT');for(const [key,value] of Object.entries(v)){insist(typeof value==='number'?Number.isFinite(value)&&Math.abs(value)<=20000:typeof value==='string'?value.length<=180&&!/[<>\\]/.test(value)&&!/(?:url\s*\(|javascript:|data:|https?:|file:)/i.test(value):typeof value==='boolean','动画值无效','CUSTOM_SCRIPT');if(['opacity','autoAlpha'].includes(key))insist(value>=0&&value<=1,'透明度无效','CUSTOM_SCRIPT');if(['scale','scaleX','scaleY'].includes(key))insist(value>=0&&value<=10,'缩放越界','CUSTOM_RESOURCE');}}
    const end=vars.at(-1),duration=method==='set'?0:(end.duration??.5),repeat=end.repeat??0,delay=end.delay??0;insist([at,duration,repeat,delay].every(Number.isFinite)&&at>=0&&duration>=0&&delay>=0&&Number.isInteger(repeat)&&repeat>=0&&repeat<=20&&at+delay+duration*(repeat+1)<=scene.durationFrames/30+.001,`场景 ${scene.id} 仅 ${scene.durationFrames/30} 秒；${selector} 的 tl.${method} 从 ${at} 秒开始，delay=${delay}、duration=${duration}、repeat=${repeat}，结束于 ${at+delay+duration*(repeat+1)} 秒。请将本场所有调用结束时间保持在 ${scene.durationFrames/30} 秒以内且重复次数为 0—20 的整数`,'CUSTOM_DURATION');
    args[0]='#'+resolveId(selector.slice(1));args[args.length-1]=at+scene.startFrame/30;calls.push({method,args,elementId:selector.slice(1)});
  }
  insist(Array.isArray(bundle.motionTargets)&&(bundle.motionTargets.length>0||staticLayout)&&bundle.motionTargets.length<=20&&bundle.motionTargets.every(id=>mapped.has(id)&&calls.some(c=>c.elementId===id&&c.method!=='set')),'自定义场景缺少可验证运动目标','CUSTOM_MOTION');
  const sampleTimes=[...new Set(calls.flatMap(c=>{const vars=c.args.at(-2),at=c.args.at(-1)+(vars.delay||0),duration=c.method==='set'?0:vars.duration??.5;return Array.from({length:(vars.repeat||0)+1},(_,i)=>[at+duration*i+duration/2,at+duration*(i+1)]).flat();}).filter(t=>t>=scene.startFrame/30&&t<(scene.startFrame+scene.durationFrames)/30))].sort((a,b)=>a-b);
  insist(sampleTimes.length<=400,'自定义场景关键过程帧过多','CUSTOM_RESOURCE');
  const hardKills=calls.flatMap(c=>{if(!['to','fromTo'].includes(c.method))return [];const v=c.args.at(-2),property=v.opacity===0?'opacity':v.autoAlpha===0?'autoAlpha':null;if(!property||v.yoyo)return [];const at=c.args.at(-1)+(v.delay||0)+(v.duration??.5)*((v.repeat||0)+1);return [`tl.set(${stringify(c.args[0])},{${property}:0},${Number(at.toFixed(6))});`];});
  return {html:serialize(tree),css:sheet.toString(),timeline:[...calls.map(c=>`tl.${c.method}(${c.args.map(stringify).join(',')});`),...hardKills].join('\n'),objects,motionTargets:bundle.motionTargets.map(resolveId),managedVideoNodeIds:managedMedia?objects.filter(o=>videoBindings.has(o.elementId)).map(o=>o.nodeId):[],sampleTimes,parameters:values};
}
