import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import http from 'node:http';
import net from 'node:net';
import sharp from 'sharp';
import puppeteer from 'puppeteer-core';
import {ROOT,defaults,verifyVideo,runtimeEnv} from '../lib/workflow.mjs';
import {planShots,validateShots,layouts} from '../lib/multishot.mjs';
import {validateSettings} from '../lib/demo-planner.mjs';

// Isolated project storage and server: never rewrites the user's projects.
const run=path.join(ROOT,'outputs','acceptance',new Date().toISOString().replace(/[:.]/g,'-'));
const freePort=()=>new Promise((resolve,reject)=>{const socket=net.createServer();socket.once('error',reject);socket.listen(0,'127.0.0.1',()=>{const port=socket.address().port;socket.close(()=>resolve(port));});});
const dataDir=path.join(run,'projects'),port=process.env.VIDEO_AGENT_TEST_PORT?Number(process.env.VIDEO_AGENT_TEST_PORT):await freePort(),base=`http://127.0.0.1:${port}`;
await fs.mkdir(dataDir,{recursive:true});
const checks=[],errors=[];let server,browser,log='';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function check(name,fn){try{await fn();checks.push({name,passed:true});console.log('PASS '+name);}catch(e){checks.push({name,passed:false,error:e.message});throw e;}}
async function api(route,options={},status=200){const r=await fetch(base+route,{signal:AbortSignal.timeout(15000),...options});const b=await r.json();assert.equal(r.status,status,JSON.stringify(b));return b;}
const json=(body,method='POST')=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
async function start(){
 const startOffset=log.length;
 server=spawn(process.execPath,['server.mjs'],{cwd:ROOT,windowsHide:true,env:{...process.env,VIDEO_AGENT_PORT:String(port),VIDEO_AGENT_DATA_DIR:dataDir,VIDEO_AGENT_EDIT_DATA_DIR:path.join(run,'edit-projects'),VIDEO_AGENT_CREATIVE_DATA_DIR:path.join(run,'creative-projects'),VIDEO_AGENT_LIVE_CODEX:'0'},stdio:['ignore','pipe','pipe']});
 server.stdout.on('data',b=>log+=b);server.stderr.on('data',b=>log+=b);
 for(let n=0;n<100;n++){if(server.exitCode!==null)throw Error('Test server exited: '+log.slice(startOffset));if(log.slice(startOffset).includes('对话视频剪辑 '+base)){try{await api('/api/health');return;}catch{}}await delay(100);}
 throw Error('Isolated server did not start');
}
async function stop(){if(server&&server.exitCode===null){const ended=once(server,'exit');server.kill();await ended;}}
function form(settings={duration:15},extra={}){const f=new FormData();f.set('brief',JSON.stringify(defaults));f.set('settings',JSON.stringify(settings));f.set('useExample','true');for(const [k,v]of Object.entries(extra))f.set(k,v);return f;}
async function create(settings,extra){return api('/api/projects',{method:'POST',body:form(settings,extra)},201);}
async function waitComplete(id){const end=Date.now()+240000;while(Date.now()<end){const p=await api('/api/projects/'+id);if(p.status==='failed')throw Error(p.error);if(p.status==='complete')return p;await delay(1000);}throw Error('Render exceeded four minutes');}
try{
 await check('时间轴：10–180 秒、24 镜头上限、连续且精确到帧',()=>{for(const duration of [10,15,25,30,60,90,120,180,31.1]){const shots=validateShots(planShots(defaults,{duration},12),12);assert.equal(shots.at(-1).end,Math.round(duration*30)/30);assert(shots.length<=24);shots.forEach((s,i)=>assert.equal(s.start,i?shots[i-1].end:0));}});
 await check('非法设置与镜头边界被拒绝',()=>{for(const v of [null,[],3,'bad',{duration:9},{duration:181},{aspect:'wide'},{quality:'8K'}])assert.throws(()=>validateSettings(v));const s=planShots(defaults,{duration:30},1);for(const patch of [{duration:1},{duration:13},{image:12},{headline:''},{copy:'字'.repeat(49)},{layout:'invalid'}])assert.throws(()=>validateShots([{...s[0],...patch},...s.slice(1)],1));assert.throws(()=>validateShots([s[0],s[0],s[1]],1));});
 await start();
 await check('构建产物、健康检查与静态资源可用',async()=>{for(const route of ['/','/app.js','/style.css'])assert.equal((await fetch(base+route)).status,200);assert.equal((await api('/api/health')).version,'0.7.0-conversation');assert.equal((await api('/api/projects')).length,0);});
 await check('本地 Host / Origin 防护与未知地址',async()=>{const status=await new Promise((resolve,reject)=>{http.get(base+'/api/health',{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject);});assert.equal(status,403);await api('/api/optimize',{...json({text:'商品是保温杯，卖点是轻巧'}),headers:{Origin:'https://evil.example'}},403);await api('/missing',{},404);});
 await check('异常 JSON、空值和超限请求返回 400/413',async()=>{for(const v of [null,[],42,'bad'])await api('/api/optimize',json(v),400);await api('/api/optimize',{method:'POST',body:'{'},400);await api('/api/optimize',json({text:'x'.repeat(17000)}),413);await api('/api/projects',{method:'POST',body:form(null)},400);});
 await check('本地提取、缺失信息与在线模型快速失败',async()=>{const p=await api('/api/optimize',json({text:'品牌是青序，商品是保温杯，卖点是轻巧、便携。'}));assert.equal(p.product,'保温杯');assert.equal(p.brand,'青序');const missing=await api('/api/optimize',json({text:'我想做一支温暖的短片。'}));assert(missing.missing.includes('商品名'));const started=Date.now();await api('/api/optimize',json({mode:'live',text:'我想制作商品短片。'}),503);assert(Date.now()-started<2000);});
 await check('无图、伪造图片、13 张素材与空商品被拒绝',async()=>{const no=form();no.set('useExample','false');await api('/api/projects',{method:'POST',body:no},400);const bad=form();bad.append('images',new Blob(['not a png'],{type:'image/png'}),'bad.png');await api('/api/projects',{method:'POST',body:bad},400);const too=form();for(let n=0;n<13;n++)too.append('images',new Blob(['x'],{type:'image/png'}),'x.png');await api('/api/projects',{method:'POST',body:too},400);await create(undefined,{brief:JSON.stringify({...defaults,product:''})}).then(()=>assert.fail('accepted empty product'),e=>assert.match(e.message,/400/));});
 let uploaded;
 await check('12 张真实图片上传、独立访问与越界隔离',async()=>{const f=form();for(let n=0;n<12;n++){const b=await sharp({create:{width:64,height:64,channels:3,background:{r:n*20,g:120,b:90}}}).png().toBuffer();f.append('images',new Blob([b],{type:'image/png'}),`image${n}.png`);}uploaded=await api('/api/projects',{method:'POST',body:f},201);assert.equal(uploaded.assetCount,12);for(const url of uploaded.imageUrls)assert.equal((await fetch(base+url)).status,200);await api(`/api/projects/${uploaded.id}/image/13`,{},404);await api(`/api/projects/${uploaded.id}/video`,{},409);await api(`/api/projects/${uploaded.id}/studio`,{method:'POST'},409);});
 await check('缺失媒体返回404且服务存活；新检出默认示例可播放',async()=>{const image=path.join(dataDir,uploaded.id,'assets/product12.png'),missing=image+'.test-missing';await fs.rename(image,missing);try{await api(uploaded.imageUrls[11],{},404);assert.equal((await api('/api/health')).ok,true);}finally{await fs.rename(missing,image);}const sample=await fetch(base+'/sample/video',{method:'HEAD'});assert.equal(sample.status,200);assert.equal(sample.headers.get('content-type'),'video/mp4');assert(Number(sample.headers.get('content-length'))>0);});
 let revision;
 await check('分镜保存为独立版本，原版本和素材不被覆盖',async()=>{const p=await create({duration:15,aspect:'9:16',quality:'4K'});assert(p.renderNotice);assert.equal(p.actualSettings.aspect,'16:9');const scenes=layouts.map((layout,i)=>({...p.storyboard[0],id:'shot-test-'+i,layout,duration:2,headline:i===0?'验收，成片测试':defaults.product,copy:i===6?'QING':'真实素材与可编辑文案'}));revision=await api(`/api/projects/${p.id}/storyboard`,json({storyboard:scenes},'PATCH'),201);assert.equal(revision.parentId,p.id);assert.equal(revision.actualSettings.duration,14);assert.equal(revision.brief.duration,14);assert.equal((await api(`/api/projects/${p.id}`)).storyboard.length,4);await api(`/api/projects/${p.id}/storyboard`,json(null,'PATCH'),400);await api(`/api/projects/${p.id}/storyboard`,json({storyboard:[]},'PATCH'),400);});
 await check('七种版式真实检查与渲染；重复提交不创建重复项目',async()=>{await api(`/api/projects/${revision.id}/render`,{method:'POST'},202);await api(`/api/projects/${revision.id}/render`,{method:'POST'},202);await api(`/api/projects/${revision.id}/storyboard`,json({storyboard:revision.storyboard},'PATCH'),409);revision=await waitComplete(revision.id);const media=await verifyVideo(path.join(dataDir,revision.id,'video.mp4'),{duration:14,width:1280,height:720});assert.equal(media.videoCodec,'h264');assert.equal(media.audioCodec,'aac');assert.match(await fs.readFile(path.join(dataDir,revision.id,'check.log'),'utf8'),/passed/i);});
 await check('MP4 播放 Range、HEAD、下载及无效范围',async()=>{const url=base+revision.videoUrl;let r=await fetch(url,{headers:{Range:'bytes=0-99'}});assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,100);r=await fetch(url,{headers:{Range:'bytes=-100'}});assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,100);for(const range of ['bytes=-0','bytes=999999999999-','bytes=5-2','invalid'])assert.equal((await fetch(url,{headers:{Range:range}})).status,416);r=await fetch(url+'?download=1',{method:'HEAD'});assert.equal(r.status,200);assert.match(r.headers.get('content-disposition'),/attachment/);assert.equal((await r.arrayBuffer()).byteLength,0);});
 await check('服务重启保留成品；中断任务转为可重试状态',async()=>{await stop();const file=path.join(dataDir,uploaded.id,'project.json'),p=JSON.parse(await fs.readFile(file));p.status='rendering';await fs.writeFile(file,JSON.stringify(p));await start();assert.equal((await api('/api/projects/'+revision.id)).status,'complete');const interrupted=await api('/api/projects/'+uploaded.id);assert.equal(interrupted.status,'failed');assert.match(interrupted.error,/重启/);assert.equal(interrupted.assetCount,12);});

 browser=await puppeteer.launch({executablePath:runtimeEnv().HYPERFRAMES_BROWSER_PATH,headless:true,defaultViewport:{width:1440,height:1000},args:['--disable-dev-shm-usage']});
 const page=await browser.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER ERROR: '+e.message);});
 await check('真实 Chrome：首屏入口、案例加载与无脚本异常',async()=>{await page.goto(base+'/create',{waitUntil:'networkidle0'});await page.waitForSelector('.case-card');assert.equal(await page.$$eval('.case-card',x=>x.length),4);assert.equal(await page.$eval('#plan-button',e=>e.disabled),false);assert.equal(await page.$eval('#description',e=>e.closest('form').querySelectorAll('[required]').length),0);await page.screenshot({path:path.join(run,'desktop.png')});assert.deepEqual(errors,[]);});
 await check('真实 Chrome：设置摘要同步、输入提取与素材上传',async()=>{await page.click('#sample');await page.click('.settings details summary');await page.select('#setting-duration','15');assert.match(await page.$eval('#settings-summary',e=>e.textContent),/15 秒/);await page.click('#optimize');await page.waitForFunction(()=>document.querySelector('#optimize').disabled===false);assert.equal(await page.$eval('[name=product]',e=>e.value),'青柠气泡水');await (await page.$('#images')).uploadFile(path.join(ROOT,'assets/cases/qing.png'));await page.waitForFunction(()=>document.querySelector('#asset-note').textContent.includes('1 张'));});
 await check('真实 Chrome：主生成按钮完成新项目与可播放 MP4',async()=>{const response=page.waitForResponse(r=>r.url()===base+'/api/projects'&&r.request().method()==='POST');await page.click('#plan-button');const created=await (await response).json();await waitComplete(created.id);await page.waitForFunction(()=>document.querySelector('#project-badge').textContent==='已完成',{timeout:20000});await page.waitForFunction(()=>document.querySelector('#video').readyState>=2);assert.equal(await page.$eval('#video',e=>Math.round(e.duration)),15);await page.$eval('#video',e=>{e.currentTime=7;});await page.waitForFunction(()=>Math.abs(document.querySelector('#video').currentTime-7)<.1);});
 await check('真实 Chrome：分镜可编辑、添加排序删除、保存与旧版隔离',async()=>{await page.click('#edit-storyboard');await page.waitForSelector('[data-shot-duration]');assert.equal(await page.$$eval('[data-shot-duration]',x=>x.length),4);const first=await page.$('[data-scene-headline]');await first.click();await first.evaluate(el=>el.select());assert.equal(await first.evaluate(el=>el.selectionEnd-el.selectionStart),await first.evaluate(el=>el.value.length));await first.type('ACCEPTANCE');await page.click('#add-shot');assert.equal(await page.$$eval('[data-shot-duration]',x=>x.length),5);assert.equal(await page.$eval('[data-scene-headline]',e=>e.value),'ACCEPTANCE');await page.$eval('.shot-actions button:nth-child(2)',e=>e.click());assert.equal(await page.$$eval('[data-scene-headline]',x=>x[1].value),'ACCEPTANCE');await page.$eval('.shot-actions button:last-child',e=>e.click());assert.equal(await page.$$eval('[data-shot-duration]',x=>x.length),4);const response=page.waitForResponse(r=>r.request().method()==='PATCH');await page.click('#save-plan');const saved=await (await response).json();assert.equal(saved.status,'awaiting_confirmation');assert.equal((await api('/api/projects/'+saved.parentId)).status,'complete');await page.waitForFunction(()=>document.querySelector('#save-plan').textContent==='分镜已保存');await page.screenshot({path:path.join(run,'storyboard.png')});});
 await check('真实 Chrome：375px 移动视口无横向溢出',async()=>{await page.setViewport({width:375,height:812});await page.screenshot({path:path.join(run,'mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewport({width:1440,height:1000});});
 await check('真实 Chrome：网络失败停止重试并可重新连接',async()=>{
  // A test fixture supplies a queued state, without launching another renderer.
  await stop();const file=path.join(dataDir,uploaded.id,'project.json'),p=JSON.parse(await fs.readFile(file));p.status='awaiting_confirmation';await fs.writeFile(file,JSON.stringify(p));await start();
  await page.reload({waitUntil:'networkidle0'});await page.setRequestInterception(true);let selected=false,failures=0;
  const networkHandler=req=>{if(req.isInterceptResolutionHandled())return;if(req.url()===base+'/api/projects/'+uploaded.id){if(!selected){selected=true;req.respond({status:200,contentType:'application/json',body:JSON.stringify({...uploaded,status:'queued'})});}else{failures++;req.abort('connectionfailed');}}else req.continue();};page.on('request',networkHandler);
  // Click the matching history card using its rendered text/order.
  const list=await api('/api/projects');const position=list.slice(0,8).findIndex(p=>p.id===uploaded.id);assert(position>=0);await page.$$eval('#history .history-card',(nodes,i)=>nodes[i].click(),position);
  await page.waitForFunction(()=>!document.querySelector('#refresh-status').hidden,{timeout:30000});assert.equal(failures,3);assert.match(await page.$eval('#result-error',e=>e.textContent),/暂停自动刷新/);page.off('request',networkHandler);await page.setRequestInterception(false);await page.click('#refresh-status');await page.waitForFunction(()=>document.querySelector('#refresh-status').hidden);assert.match(await page.$eval('#project-badge',e=>e.textContent),/待确认/);
 });
 await check('浏览器完整流程无未捕获 JavaScript 异常',()=>assert.deepEqual(errors,[]));
}catch(e){console.error(e.stack);process.exitCode=1;}
finally{
 if(browser)await browser.close();await stop();await fs.writeFile(path.join(run,'server.log'),log);
 const report={date:new Date().toISOString(),scope:'isolated API + real Chrome + real HyperFrames render',passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks,browserErrors:errors,run};
 await fs.writeFile(path.join(run,'report.json'),JSON.stringify(report,null,2));await fs.writeFile(path.join(ROOT,'outputs/acceptance-latest.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed,run}));
}

